---
sidebar: sidebar 
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, best practices, best-practices 
permalink: nas-containers.html 
summary: 이 기술 보고서에서는 NetApp ONTAP의 FlexCache 및 FlexGroup 볼륨을 개괄적으로 비롯하여 모범 사례 권장사항을 제공합니다 
---
= FlexCache 및 FlexGroup 볼륨 기술 보고서
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp NAS 솔루션은 데이터 관리를 단순화하며 비용을 최적화하는 동시에 규모 확장에 대비할 수 있도록 지원합니다. ONTAP NAS 솔루션은 유니파이드 아키텍처 내에서 무중단 운영과 검증된 효율성, 무한한 확장성을 제공합니다. ONTAP을 기반으로 하는 스케일아웃 NAS는 대규모 ONTAP 에코시스템을 활용하여 혁신을 주도하고 공격적인 미래 혁신을 위한 비전을 실현할 수 있습니다.

[NOTE]
====
이러한 기술 보고서는 에서 확장됩니다 link:https://docs.netapp.com/us-en/ontap/task_nas_flexcache.html["ONTAP FlexCache 볼륨"] 및 link:https://docs.netapp.com/us-en/ontap/task_nas_provision_flexgroup.html["ONTAP FlexGroup 볼륨"] 제품 설명서.

====


== FlexCache

link:https://www.netapp.com/pdf.html?item=/media/7336-tr4743.pdf["TR-4743: ONTAP의 FlexCache"^]
FlexCache는 동일하거나 다른 ONTAP 클러스터에서 볼륨의 쓰기 가능한 스파스 복제본을 생성하는 캐싱 기술입니다. 데이터 및 파일을 사용자와 더 가까운 곳에 제공하여 더 적은 설치 공간으로 더 빠른 처리량을 얻을 수 있습니다. FlexCache 사용 방법, 권장 사례, 제한 및 설계 및 구현 고려 사항에 대해 알아보십시오.



== FlexGroup 볼륨

link:https://www.netapp.com/pdf.html?item=/media/17251-tr4571a.pdf["TR-4571a: FlexGroup의 10대 모범 사례"^]
이 기술 보고서는 빠른 사용을 위한 TR-4571:NetApp ONTAP FlexGroup 볼륨 모범 사례 및 구현 가이드의 요약 버전입니다.

link:https://www.netapp.com/pdf.html?item=/media/7337-tr4557.pdf["TR-4557: NetApp ONTAP FlexGroup 볼륨 - 기술 개요"^]
메타데이터 집약적인 워크로드에서 예측 가능하고 지연 시간이 짧은 성능과 무한 확장성을 결합한 ONTAP 스케일아웃 NAS 컨테이너인 FlexGroup 볼륨에 대해 알아보십시오.

link:https://www.netapp.com/pdf.html?item=/media/12385-tr4571.pdf["TR-4571: NetApp ONTAP FlexGroup 볼륨 모범 사례 및 구현 가이드"^]
FlexGroup 볼륨, 권장 사례 및 구현 팁에 대해 알아보십시오. FlexGroup 볼륨은 메타데이터가 많은 워크로드에서 거의 무제한의 용량과 예측 가능하고 짧은 지연 시간의 성능을 결합한 ONTAP 스케일아웃 NAS 컨테이너의 발전된 형태입니다.

link:https://www.netapp.com/pdf.html?item=/media/17064-tr4678.pdf["TR-4678: FlexGroup 볼륨의 데이터 보호 및 백업"^]
스냅샷 복사본, SnapMirror, 기타 데이터 보호 및 백업 솔루션을 포함한 FlexGroup 볼륨의 데이터 보호 및 백업에 대해 알아보십시오.
