---
settings:
  name: ONTAP Technical Reports
  search: ontap-technical-reports, ontap-apps-dbs, netapp-solutions-sap
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: ONTAP 기술 보고서
    url: "/index.html"
  - title: 제공합니다
    url: "/apps-dbs.html"
  - title: 비즈니스 연속성
    url: "/business-continuity.html"
  - title: 데이터 보호 및 재해 복구
    url: "/data-protection-disaster-recovery.html"
  - title: FlexCache 및 FlexGroup 볼륨
    url: "/nas-containers.html"
  - title: NAS
    url: "/nas.html"
  - title: 네트워킹
    url: "/networking.html"
  - title: 산
    url: "/san.html"
  - title: 보안
    url: "/security.html"
  - title: 보안 강화 가이드
    url: "/security-hardening-guides.html"
  - title: SnapCenter
    url: "/snapcenter.html"
  - title: 계층화
    url: "/tiering.html"
  - title: 포함되었습니다
    url: "/virtualization.html"
  - title: 법적 고지
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
