---
sidebar: sidebar 
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, MAV, MFA, Ransomware, Security, best practices, best-practices, tamperproof, tamper proof, tamperproof snapshots tamper-proof snapshots 
permalink: security.html 
summary: 이러한 기술 보고서에서는 NetApp ONTAP의 보안 개요와 권장 사례를 제공합니다. 
---
= 보안 기술 보고서
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP는 보안을 솔루션의 일부로 통합하여 지속적으로 발전하고 있습니다. ONTAP의 최신 릴리즈에는 조직이 하이브리드 클라우드 전체에서 데이터를 보호하고, 랜섬웨어 공격을 방지하고, 업계 권장 사례를 준수하는 데 매우 중요한 새로운 보안 기능이 다수 포함되어 있습니다. 이러한 새로운 기능은 조직의 Zero Trust 모델 전환도 지원합니다.

[NOTE]
====
이러한 기술 보고서는 에서 확장됩니다 link:https://docs.netapp.com/us-en/ontap/security-encryption/index.html["ONTAP 보안 및 데이터 암호화"] 제품 설명서.

====


== 랜섬웨어

link:https://www.netapp.com/pdf.html?item=/media/7334-tr4572.pdf["TR-4572: 랜섬웨어용 NetApp 솔루션"^]
랜섬웨어의 발전 과정 및 랜섬웨어에 대한 NetApp 솔루션을 사용하여 공격을 식별하고, 확산을 방지하고, 가능한 한 빨리 복구하는 방법에 대해 알아보십시오. 이 문서에 제공된 지침과 솔루션은 조직이 사이버 복원력 있는 솔루션을 보유하면서 정보 시스템의 기밀성, 무결성 및 가용성에 대해 규정된 보안 목표를 충족할 수 있도록 설계되었습니다.

link:https://www.netapp.com/pdf.html?item=/media/6158-tr4526.pdf["TR-4526: NetApp SnapLock를 사용한 규정 준수 WORM 스토리지"^]
많은 기업에서는 규정 준수 요구 사항을 충족하거나 단순히 데이터 보호 전략에 다른 계층을 추가하기 위해 WORM(Write Once, Read Many) 데이터 스토리지를 사용하고 있습니다. ONTAP에서 WORM 솔루션인 SnapLock를 WORM 데이터 스토리지가 필요한 환경에 통합하는 방법에 대해 알아보십시오.



== 제로 트러스트

link:https://www.netapp.com/pdf.html?item=/media/19756-tr-4829.pdf["TR-4829: NetApp and Zero Trust"^]
제로 트러스트는 일반적으로 마이크로 코어 및 주변 장치(MCAP)를 설계하여 데이터, 서비스, 애플리케이션 또는 자산을 세그먼트 게이트웨이라고 하는 제어 기능으로 보호하는 네트워크 중심 접근 방식이었습니다. ONTAP는 제로 트러스트에 대한 데이터 중심 접근 방식을 취합니다. 이 접근 방식은 스토리지 관리 시스템이 고객 데이터 액세스를 보호하고 모니터링하기 위한 세분화 게이트웨이가 됩니다. 특히 FPolicy Zero Trust 엔진과 FPolicy 파트너 에코시스템은 정상 및 비정상적인 데이터 액세스 패턴을 세부적으로 이해하고 내부자 위협을 식별하기 위한 제어 센터가 됩니다.



== 다단계 인증

link:https://www.netapp.com/pdf.html?item=/media/17055-tr4647.pdf["TR-4647: ONTAP 모범 사례 및 구현 가이드의 다중 요소 인증"^]
System Manager, Active IQ Unified Manager 및 ONTAP SSH(Secure Shell) CLI 인증을 사용하여 관리 액세스에 대한 ONTAP의 다단계 인증 기능에 대해 알아보십시오.

link:https://www.netapp.com/pdf.html?item=/media/17036-tr4717.pdf["TR-4717: 공통 액세스 카드를 사용한 ONTAP SSH 인증"^]
ONTAP에서 CAC(Common Access Card)에 저장된 공개 키를 통해 ONTAP 스토리지 관리자를 인증하기 위해 ActivClient 소프트웨어와 함께 타사 SSH 클라이언트를 구성 및 테스트하는 방법을 알아봅니다.



== 멀티 테넌시

link:https://www.netapp.com/pdf.html?item=/media/16886-tr-4160.pdf["TR-4160: ONTAP의 보안 멀티 테넌시"^]
설계 고려 사항 및 권장 사례를 비롯하여 ONTAP에서 스토리지 VM을 사용하여 보안 멀티 테넌시를 구현하는 방법에 대해 알아보십시오.



== 로깅

link:https://www.netapp.com/pdf.html?item=/media/103610-tr-4303i-0514-logging-in-clustered-dot.pdf["TR-4303: ONTAP에 로그인"^]
ONTAP에서 생성된 다양한 로그, 제공되는 기능 및 로그를 보고 액세스하는 방법을 알아봅니다.



== 표준

link:https://www.netapp.com/pdf.html?item=/media/17180-tr4401.pdf["TR-4401: PCI-DSS 4.0 및 ONTAP"^]
PCI DSS 4.0 표준에 따라 시스템을 검증하고 NetApp ONTAP 시스템에 적용하는 제어 요구 사항을 충족하는 방법에 대해 알아보십시오.
