---
layout: landing-page 
sidebar: sidebar 
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, best practices, best-practices 
permalink: snapcenter.html 
summary: 이러한 기술 보고서에서는 SnapCenter with NetApp ONTAP에 대한 개요와 권장 사례를 제공합니다. 
---
= SnapCenter 기술 보고서
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter은 애플리케이션 정합성이 보장되는 데이터 보호 및 클론 관리를 위한 유니파이드 플랫폼을 제공합니다. SnapCenter는 애플리케이션 통합 워크플로우를 활용해 백업, 복원, 클론 라이프사이클 관리를 단순화합니다. SnapCenter는 스토리지 기반 데이터 관리를 활용하여 성능과 가용성을 향상하고 테스트 및 개발 시간을 단축합니다.

[NOTE]
====
이러한 기술 보고서는 에서 확장됩니다 link:https://docs.netapp.com/us-en/snapcenter/index.html["SnapCenter"] 제품 설명서.

====


== Oracle용 SnapCenter

link:https://www.netapp.com/pdf.html?item=/media/12403-tr4700.pdf["TR-4700: Oracle 데이터베이스 모범 사례를 위한 SnapCenter 플러그인"^]
NetApp SnapCenter는 Oracle의 일관된 데이터 보호를 위한 확장 가능한 통합 플랫폼으로, 중앙 집중식 제어 및 감독을 통해 복잡한 작업을 자동화합니다. SnapCenter를 사용하여 Oracle 데이터베이스를 구축하는 데 권장되는 방법에 대해 알아보십시오.

link:https://docs.netapp.com/us-en/netapp-solutions/databases/snapctr_svcs_ora.html["TR-4964: SnapCenter 서비스를 사용하여 Oracle 데이터베이스 백업, 복원 및 클론 복제"]
ONTAP 스토리지와 EC2 컴퓨팅 인스턴스를 위해 Amazon FSx에 구축된 Oracle 데이터베이스를 백업, 복원 및 클론 복제하도록 SnapCenter 서비스를 설정하는 방법에 대해 알아보십시오. SnapCenter 서비스는 설정 및 사용이 훨씬 간편하지만 SnapCenter 인터페이스를 통해 사용할 수 있는 주요 기능을 제공합니다.



== Microsoft SQL Server용 SnapCenter

link:https://www.netapp.com/pdf.html?item=/media/12400-tr4714.pdf["TR-4714: NetApp SnapCenter를 사용하는 Microsoft SQL Server의 모범 사례"^]
SnapCenter를 사용하여 NetApp 스토리지에 Microsoft SQL Server를 성공적으로 구축하여 데이터를 보호하는 방법에 대해 알아보십시오.



== Microsoft Exchange Server용 SnapCenter

link:https://www.netapp.com/es/pdf.html?item=/es/media/12398-tr-4681.pdf["TR-4681: NetApp SnapCenter를 사용하는 Microsoft Exchange Server에 대한 모범 사례"^]
데이터 보호를 위해 SnapCenter를 사용하여 NetApp 스토리지에 Microsoft Exchange Server를 성공적으로 구축하는 방법에 대해 알아보십시오.



== SAP HANA용 SnapCenter

link:https://docs.netapp.com/us-en/netapp-solutions-sap/backup/saphana-br-scs-overview.html["TR-4614: SnapCenter를 통한 SAP HANA 백업 및 복구"]
SnapCenter는 SAP HANA 및 기타 데이터베이스를 위한 애플리케이션 정합성 보장 데이터 보호를 위한 확장 가능한 유니파이드 플랫폼입니다. SnapCenter는 중앙 집중식 제어 및 감독을 지원하면서 사용자가 애플리케이션별 백업, 복원 및 클론 작업을 관리할 수 있는 기능을 위임합니다. 데이터베이스 및 스토리지 관리자는 SnapCenter를 사용하여 다양한 애플리케이션과 데이터베이스의 백업, 복원, 클론 복제 작업을 관리하는 단일 툴에 대해 알아보십시오.

link:https://docs.netapp.com/us-en/netapp-solutions-sap/backup/amazon-fsx-overview.html["TR-4926: NetApp ONTAP용 Amazon FSx 기반 SAP HANA - SnapCenter를 통한 백업 및 복구"]
NetApp ONTAP 및 SnapCenter용 Amazon FSx에서 SAP HANA 데이터 보호를 위한 권장 사례를 확인하십시오. 이 플레이북에서는 SnapCenter 개념, 구성 권장사항, 구성, 백업 작업, 복원 및 복구 작업을 수행할 수 있습니다.

link:https://docs.netapp.com/us-en/netapp-solutions-sap/lifecycle/sc-copy-clone-introduction.html["TR-4667: SnapCenter를 사용하여 SAP HANA 시스템 복사 및 클론 작업 자동화"]
SnapCenter 스토리지 클론 복제와 사전 클론 복제 및 사후 클론 복제 작업을 유연하게 정의하는 옵션을 통해 SAP Basis 관리자는 SAP 시스템 복사, 클론 복제 또는 업데이트 작업을 가속화 및 자동화할 수 있습니다. 지금 알아보기 운영 스토리지 또는 2차 스토리지에서 SnapCenter 스냅샷 백업을 선택하면 논리적 손상, 재해 복구 테스트 또는 SAP QA 시스템 업데이트 등 가장 중요한 사용 사례를 해결할 수 있습니다.

link:https://www.netapp.com/pdf.html?item=/media/17030-tr4719.pdf["TR-4719: SnapCenter를 통해 SAP HANA 시스템 복제 백업 및 복구"^]
SAP HANA 시스템 복제 환경에서 SnapCenter 기술과 SAP HANA 플러그인을 사용하여 백업 및 복구를 수행하는 방법에 대해 알아보십시오.

link:https://docs.netapp.com/us-en/netapp-solutions-sap/lifecycle/sc-copy-clone-introduction.html["TR-4667: SnapCenter를 사용하여 SAP HANA 시스템 복사 및 클론 작업 자동화"]
스토리지 계층에서 애플리케이션 정합성이 보장된 NetApp 스냅샷 백업을 생성하는 기능은 시스템 복사본 및 시스템 클론 복제 작업을 위한 기반입니다. 스토리지 기반 스냅샷 백업은 SAP HANA용 NetApp SnapCenter 플러그인과 SAP HANA 데이터베이스에서 제공하는 인터페이스를 사용하여 생성됩니다. SnapCenter는 SAP HANA 백업 카탈로그에 Snapshot 백업을 등록하여 복원 및 복구뿐만 아니라 클론 복제 작업에 백업을 사용할 수 있습니다.



== SnapCenter 강화 가이드

link:https://www.netapp.com/pdf.html?item=/media/82393-tr-4957.pdf["TR-4957: NetApp SnapCenter 보안 강화 가이드"^]
조직에서 정보 시스템 기밀성, 무결성 및 가용성에 대해 규정된 보안 목표를 충족할 수 있도록 SnapCenter를 구성하는 방법을 알아보십시오.
